version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: ./ScheduleIS/Dockerfile # укажите путь к вашему Dockerfile для ASP.NET Core
    ports:
      - "8080:8080"
      - "7076:7076"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgre;Database=scheduledb;Username=postgres;Password=admin
    depends_on:
      - postgres
    
  nextjs:
    build:
      context: ./Frontend/schedule
      dockerfile: dockerfile # укажите путь к вашему Dockerfile для Next.js
    ports:
      - "3000:3000"

  postgres:
   container_name: postgres
   image: postgres:latest
   environment:
    POSTGRES_DB: "scheduledb"
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "admin"
   volumes:
    - postgres-data:/var/lib/postgresql/data
   ports:
    - "5432:5432"

volumes:
 postgres-data:
